[package]
name = "kajet-mcp"
version = "0.1.0"
edition = "2021"

[dependencies]
kajet-core = { path = "../core" }

rmcp = { version = "0.8", features = ["server", "transport-io"] }
schemars = "0.8"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
chrono = "0.4"
rust-i18n = "3"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["test-util", "macros"] }
